# Generated by Django 2.1.3 on 2018-11-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
    ]
